version: "3.8"
services:
  db:
    image: mysql:8.0
    env_file:
      - .env.prod
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  api:
    build: .
    container_name: custom-qrs
    depends_on:
      - db
    ports:
      - "8000:8000"
volumes:
  db_data:
